Decoder_arg={
        "output_dir": None,
        "overwrite_output_dir": True,
        "do_train": True,
        "do_eval": True,
        "per_device_train_batch_size": 1,
        "per_device_eval_batch_size": 1,
        "learning_rate": 3e-5,
        "adam_beta1": 0.9,
        "adam_beta2": 0.999,
        "adam_epsilon": 1e-3,
        "num_train_epochs": 1,
        "warmup_steps": 120,
        "evaluation_strategy": "no",
        "logging_strategy": "steps",
        "logging_steps": 5,
        "save_strategy": "steps",
        "save_steps": 100,
        "save_total_limit": 100,
        "bf16": True,
        "bf16_full_eval": True,
        "use_cpu": False,
        "gradient_accumulation_steps": 16,
        "dataloader_drop_last": False,
        "label_names": ["labels"],
        "prediction_loss_only": True,
        "optim": "adamw_torch",
        "report_to": "wandb",
        "gradient_checkpointing": True,
        "accelerator_config": {
            "split_batches": False,
            "dispatch_batches": True,
            "even_batches": False,
            "use_seedable_sampler": True
        }
}

Encoder_arg={
        "output_dir": None,
        "overwrite_output_dir": True,
        "do_train": True,
        "do_eval": True,
        "per_device_train_batch_size": 32,
        "per_device_eval_batch_size": 1,
        "learning_rate": 3e-4,
        "adam_beta1": 0.9,
        "adam_beta2": 0.999,
        "adam_epsilon": 1e-3,
        "num_train_epochs": 1,
        "warmup_steps": 120,
        "evaluation_strategy": "no",
        "logging_strategy": "steps",
        "logging_steps": 5,
        "save_strategy": "no",
        "save_total_limit": 1000,
        "bf16": True,
        "bf16_full_eval": True,
        "use_cpu": False,
        "gradient_accumulation_steps": 1,
        "dataloader_drop_last": False,
        "remove_unused_columns":False,
        "label_names":['labels'],
        "prediction_loss_only": True,
        "optim": "adamw_torch",
        "report_to": "wandb",
        "gradient_checkpointing": True,
        "accelerator_config": {
            "split_batches": False,
            "dispatch_batches": True,
            "even_batches": False,
            "use_seedable_sampler": True
        },
        "dataloader_num_workers":16

}
